PREFIX ex: <http://example.org/ssbw#>
PREFIX schema: <https://schema.org/>

SELECT ?producto ?nombre ?precio
WHERE {
  ?producto a ex:Producto ;
            schema:name ?nombre ;
            ex:precio ?precio .
  FILTER(?precio <= 10.00)
}
ORDER BY ?precio ?nombre
